### PR TITLE
fix: since the upgrade to the `polkadot-stable2409` version, running a chain node requires the node-key to be generated first

### PR DESCRIPTION
**Pull request by 0xbillw**

### CODE REVIEW

**Comment by sunway910** [comment]
```bash
if ! docker run --rm -v $host_base_path:$base_path cesslab/cess-chain:$image_tag key generate-node-key --base-path $base_path --chain $chain_spec > /dev/null 2>&1; then
    log_err "Error: Failed to generate node key"
    exit 1
fi
```

**Comment by 0xbillw** [comment]
> ```shell
> if ! docker run --rm -v $host_base_path:$base_path cesslab/cess-chain:$image_tag key generate-node-key --base-path $base_path --chain $chain_spec > /dev/null 2>&1; then
>     log_err "Error: Failed to generate node key"
>     exit 1
> fi
> ```

LGTM

**Review by 0xbillw — COMMENTED** [review]
This is thoughtful, but actually redundant, because the `generate-node-key` of `cess-node` returns a failure in the presence of `node-key`, which is normal. My advice is to ignore the return value.

**Review by sunway910 — APPROVED** [review]

**Review by sunway910 — APPROVED** [review]

**Review by 0xbillw — COMMENTED** [review]
try this

**Pull request merged**
